DROP TABLE IF EXISTS goals CASCADE;
CREATE TABLE goals(
    goal_id SERIAL PRIMARY KEY NOT NULL,
    goal VARCHAR(255) NOT NULL,
    user_id SERIAL FOREIGN KEY NOT NULL,
    milestone_id SERIAL FOREIGN KEY NOT NULL,
);